"""Add investment fields to recurring transactions

Revision ID: 0ab140e4c001
Revises: 158313575183
Create Date: 2026-06-03 22:09:34.322135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab140e4c001'
down_revision: Union[str, Sequence[str], None] = '158313575183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_class', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('sector', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('geographic_zone', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.drop_column('geographic_zone')
        batch_op.drop_column('sector')
        batch_op.drop_column('asset_class')

    # ### end Alembic commands ###
