"""Add recurring_transaction_id and generation fields

Revision ID: 158313575183
Revises: 2bfcde87814c
Create Date: 2026-06-03 21:48:14.697858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '158313575183'
down_revision: Union[str, Sequence[str], None] = '2bfcde87814c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('last_generated_date', sa.DateTime(), nullable=True))
    #     batch_op.add_column(sa.Column('auto_generate', sa.Boolean(), nullable=False))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurring_transaction_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_recurring_transaction_id'), ['recurring_transaction_id'], unique=False)
        batch_op.create_foreign_key('fk_transactions_recurring_transaction_id', 'recurring_transactions', ['recurring_transaction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_recurring_transaction_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_recurring_transaction_id'))
        batch_op.drop_column('recurring_transaction_id')

    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.drop_column('auto_generate')
        batch_op.drop_column('last_generated_date')

    # ### end Alembic commands ###
