"""Add ticket_date to salary_month

Revision ID: 259a569307e4
Revises: 415059010278
Create Date: 2026-06-15 22:48:50.404839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '259a569307e4'
down_revision: Union[str, Sequence[str], None] = '415059010278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_months', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_months', schema=None) as batch_op:
        batch_op.drop_column('ticket_date')

    # ### end Alembic commands ###
