"""Align recurring_transactions model

Revision ID: 2bfcde87814c
Revises: 0143092e142d
Create Date: 2026-06-03 20:18:50.460731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bfcde87814c'
down_revision: Union[str, Sequence[str], None] = 'e2f3g4h5i6j7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.alter_column('frequency',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_recurring_transactions_merchant'))
        batch_op.create_index(batch_op.f('ix_recurring_transactions_name'), ['name'], unique=False)
        batch_op.drop_column('merchant')
        batch_op.drop_column('day_of_week')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_week', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('merchant', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_index(batch_op.f('ix_recurring_transactions_name'))
        batch_op.create_index(batch_op.f('ix_recurring_transactions_merchant'), ['merchant'], unique=False)
        batch_op.alter_column('frequency',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('type')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
