"""Add dismissed_insights table

Revision ID: 32b747b91d3c
Revises: 9e6b1860ccbd
Create Date: 2026-06-15 22:00:15.979047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32b747b91d3c'
down_revision: Union[str, Sequence[str], None] = '9e6b1860ccbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dismissed_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dismissed_insights'))
    )
    with op.batch_alter_table('dismissed_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dismissed_insights_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dismissed_insights_title'), ['title'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dismissed_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dismissed_insights_title'))
        batch_op.drop_index(batch_op.f('ix_dismissed_insights_id'))

    op.drop_table('dismissed_insights')
    # ### end Alembic commands ###
