"""Add salary config and telecommuting days

Revision ID: 415059010278
Revises: 32b747b91d3c
Create Date: 2026-06-15 22:34:29.583747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '415059010278'
down_revision: Union[str, Sequence[str], None] = '32b747b91d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salary_account_id', sa.Integer(), nullable=False),
    sa.Column('ticket_account_id', sa.Integer(), nullable=False),
    sa.Column('net_salary', sa.Float(), nullable=False),
    sa.Column('ticket_value', sa.Float(), nullable=False),
    sa.Column('ticket_employee_share', sa.Float(), nullable=False),
    sa.Column('salary_category_id', sa.Integer(), nullable=True),
    sa.Column('ticket_category_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['salary_account_id'], ['accounts.id'], name=op.f('fk_salary_configs_salary_account_id_accounts')),
    sa.ForeignKeyConstraint(['salary_category_id'], ['categories.id'], name=op.f('fk_salary_configs_salary_category_id_categories')),
    sa.ForeignKeyConstraint(['ticket_account_id'], ['accounts.id'], name=op.f('fk_salary_configs_ticket_account_id_accounts')),
    sa.ForeignKeyConstraint(['ticket_category_id'], ['categories.id'], name=op.f('fk_salary_configs_ticket_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salary_configs'))
    )
    with op.batch_alter_table('salary_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salary_configs_id'), ['id'], unique=False)

    op.create_table('salary_months',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salary_config_id', sa.Integer(), nullable=False),
    sa.Column('month_label', sa.String(length=7), nullable=False),
    sa.Column('salary_date', sa.Date(), nullable=False),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salary_config_id'], ['salary_configs.id'], name=op.f('fk_salary_months_salary_config_id_salary_configs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salary_months'))
    )
    with op.batch_alter_table('salary_months', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salary_months_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_salary_months_month_label'), ['month_label'], unique=False)

    op.create_table('telecommuting_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salary_config_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('month_label', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['salary_config_id'], ['salary_configs.id'], name=op.f('fk_telecommuting_days_salary_config_id_salary_configs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telecommuting_days'))
    )
    with op.batch_alter_table('telecommuting_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telecommuting_days_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_telecommuting_days_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telecommuting_days_month_label'), ['month_label'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telecommuting_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telecommuting_days_month_label'))
        batch_op.drop_index(batch_op.f('ix_telecommuting_days_id'))
        batch_op.drop_index(batch_op.f('ix_telecommuting_days_date'))

    op.drop_table('telecommuting_days')
    with op.batch_alter_table('salary_months', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salary_months_month_label'))
        batch_op.drop_index(batch_op.f('ix_salary_months_id'))

    op.drop_table('salary_months')
    with op.batch_alter_table('salary_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salary_configs_id'))

    op.drop_table('salary_configs')
    # ### end Alembic commands ###
