"""enrich savings goals with account and category

Revision ID: 4a5c3734161b
Revises: e8a5a33db28c
Create Date: 2026-06-04 22:40:20.182292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a5c3734161b'
down_revision: Union[str, Sequence[str], None] = 'e8a5a33db28c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.alter_column('keyword',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.create_foreign_key('fk_savings_goals_category_id', 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key('fk_savings_goals_account_id', 'accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings_goals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_savings_goals_account_id', type_='foreignkey')
        batch_op.drop_constraint('fk_savings_goals_category_id', type_='foreignkey')
        batch_op.alter_column('keyword',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('category_id')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
