"""Add recurring transaction link to salary config

Revision ID: 53a87a0f2aff
Revises: 259a569307e4
Create Date: 2026-06-16 22:08:44.540879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a87a0f2aff'
down_revision: Union[str, Sequence[str], None] = '259a569307e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed accounts alteration to avoid conflict

    with op.batch_alter_table('salary_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_tt_days', sa.Integer(), nullable=False, server_default='18'))
    with op.batch_alter_table('salary_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary_day_of_month', sa.Integer(), nullable=False, server_default='25'))
    with op.batch_alter_table('salary_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_day_of_month', sa.Integer(), nullable=False, server_default='5'))
    with op.batch_alter_table('salary_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary_recurring_id', sa.Integer(), nullable=True))
    with op.batch_alter_table('salary_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_recurring_id', sa.Integer(), nullable=True))
    with op.batch_alter_table('salary_configs', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_salary_configs_ticket_recurring_id_recurring_transactions'), 'recurring_transactions', ['ticket_recurring_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_salary_configs_salary_recurring_id_recurring_transactions'), 'recurring_transactions', ['salary_recurring_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_configs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_salary_configs_salary_recurring_id_recurring_transactions'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_salary_configs_ticket_recurring_id_recurring_transactions'), type_='foreignkey')
    with op.batch_alter_table('salary_configs', schema=None) as batch_op:
        batch_op.drop_column('ticket_recurring_id')
    with op.batch_alter_table('salary_configs', schema=None) as batch_op:
        batch_op.drop_column('salary_recurring_id')
    with op.batch_alter_table('salary_configs', schema=None) as batch_op:
        batch_op.drop_column('ticket_day_of_month')
    with op.batch_alter_table('salary_configs', schema=None) as batch_op:
        batch_op.drop_column('salary_day_of_month')
    with op.batch_alter_table('salary_configs', schema=None) as batch_op:
        batch_op.drop_column('expected_tt_days')

    # Removed accounts downgrade

    # ### end Alembic commands ###
