"""Add categorization_rules table

Revision ID: 5f70692fbe6f
Revises: 4a5c3734161b
Create Date: 2026-06-06 00:02:53.309440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f70692fbe6f'
down_revision: Union[str, Sequence[str], None] = '4a5c3734161b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorization_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(length=32), nullable=True),
    sa.Column('merchant_name', sa.String(length=120), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_categorization_rules_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categorization_rules'))
    )
    with op.batch_alter_table('categorization_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorization_rules_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categorization_rules_id'), ['id'], unique=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_categories_name'), ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_categories_name'), type_='unique')

    with op.batch_alter_table('categorization_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorization_rules_id'))
        batch_op.drop_index(batch_op.f('ix_categorization_rules_category_id'))

    op.drop_table('categorization_rules')
    # ### end Alembic commands ###
