"""add transfer fields to transactions

Revision ID: 6254eed9ef0c
Revises: 3cd86e099271
Create Date: 2026-06-06 16:25:43.846127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6254eed9ef0c'
down_revision: Union[str, Sequence[str], None] = '3cd86e099271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_transfer', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('linked_transaction_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_linked_transaction_id'), ['linked_transaction_id'], unique=False)
        batch_op.create_foreign_key('fk_transactions_linked_transaction', 'transactions', ['linked_transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_linked_transaction', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_linked_transaction_id'))
        batch_op.drop_column('linked_transaction_id')
        batch_op.drop_column('is_transfer')
    # ### end Alembic commands ###
