"""simplify salary config

Revision ID: 732905a8ae66
Revises: 301effffc548
Create Date: 2026-06-16 23:28:00.704044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '732905a8ae66'
down_revision: Union[str, Sequence[str], None] = '301effffc548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_configs', schema=None) as batch_op:
        batch_op.drop_column('ticket_employee_share')
        batch_op.drop_column('salary_day_of_month')
        batch_op.drop_column('expected_tt_days')
        batch_op.drop_column('ticket_day_of_month')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_day_of_month', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False))
        batch_op.add_column(sa.Column('expected_tt_days', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))
        batch_op.add_column(sa.Column('salary_day_of_month', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False))
        batch_op.add_column(sa.Column('ticket_employee_share', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
