"""create_tags_table

Revision ID: 86010323e83a
Revises: c35f18abcd7b
Create Date: 2026-06-07 19:48:58.443495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86010323e83a'
down_revision: Union[str, Sequence[str], None] = 'c35f18abcd7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)

    op.create_table('transaction_tags',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_transaction_tags_tag_id_tags')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_transaction_tags_transaction_id_transactions')),
    sa.PrimaryKeyConstraint('transaction_id', 'tag_id', name=op.f('pk_transaction_tags'))
    )
    with op.batch_alter_table('investment_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investment_transactions_linked_transaction_id'), ['linked_transaction_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_linked_investment_transaction_id'), ['linked_investment_transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_linked_investment_transaction_id'))

    with op.batch_alter_table('investment_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investment_transactions_linked_transaction_id'))

    op.drop_table('transaction_tags')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_name'))
        batch_op.drop_index(batch_op.f('ix_tags_id'))

    op.drop_table('tags')
    # ### end Alembic commands ###
