"""add_historical_exchange_rates

Revision ID: 88272dbc341e
Revises: 0001_initial_schema
Create Date: 2026-05-19 19:30:09.958116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88272dbc341e'
down_revision: Union[str, Sequence[str], None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_exchange_rates_currency'), 'historical_exchange_rates', ['currency'], unique=False)
    op.create_index(op.f('ix_historical_exchange_rates_date'), 'historical_exchange_rates', ['date'], unique=False)
    op.create_index(op.f('ix_historical_exchange_rates_id'), 'historical_exchange_rates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historical_exchange_rates_id'), table_name='historical_exchange_rates')
    op.drop_index(op.f('ix_historical_exchange_rates_date'), table_name='historical_exchange_rates')
    op.drop_index(op.f('ix_historical_exchange_rates_currency'), table_name='historical_exchange_rates')
    op.drop_table('historical_exchange_rates')
    # ### end Alembic commands ###
