"""add investment transfer fields and ignore flag

Revision ID: c35f18abcd7b
Revises: 6254eed9ef0c
Create Date: 2026-06-06 16:37:29.736374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c35f18abcd7b'
down_revision: Union[str, Sequence[str], None] = '6254eed9ef0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_transfer', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('is_transfer_ignored', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('linked_transaction_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_itx_linked_tx', 'transactions', ['linked_transaction_id'], ['id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_transfer_ignored', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('linked_investment_transaction_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tx_linked_itx', 'investment_transactions', ['linked_investment_transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tx_linked_itx', type_='foreignkey')
        batch_op.drop_column('linked_investment_transaction_id')
        batch_op.drop_column('is_transfer_ignored')

    with op.batch_alter_table('investment_transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_itx_linked_tx', type_='foreignkey')
        batch_op.drop_column('linked_transaction_id')
        batch_op.drop_column('is_transfer_ignored')
        batch_op.drop_column('is_transfer')
    # ### end Alembic commands ###
