"""restore ticket_employee_share

Revision ID: dfb451585eec
Revises: 732905a8ae66
Create Date: 2026-06-16 23:33:04.701053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb451585eec'
down_revision: Union[str, Sequence[str], None] = '732905a8ae66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_employee_share', sa.Float(), server_default='4.20', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_configs', schema=None) as batch_op:
        batch_op.drop_column('ticket_employee_share')

    # ### end Alembic commands ###
