"""add_fonds_euros_and_investis_to_accounts

Revision ID: eba9c3ffd144
Revises: dfb451585eec
Create Date: 2026-06-23 22:03:24.583624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba9c3ffd144'
down_revision: Union[str, Sequence[str], None] = 'dfb451585eec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fonds_euros_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fonds_investis_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('fonds_investis_pct')
        batch_op.drop_column('fonds_euros_pct')
    # ### end Alembic commands ###
