"""create merchants and aliases tables

Revision ID: ece5365a3f43
Revises: d590d50503e5
Create Date: 2026-06-15 18:31:27.503130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece5365a3f43'
down_revision: Union[str, Sequence[str], None] = 'd590d50503e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_merchants_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchants'))
    )
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merchants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchants_name'), ['name'], unique=True)

    op.create_table('merchant_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_merchant_aliases_merchant_id_merchants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant_aliases'))
    )
    with op.batch_alter_table('merchant_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merchant_aliases_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchant_aliases_label'), ['label'], unique=True)
        batch_op.create_index(batch_op.f('ix_merchant_aliases_merchant_id'), ['merchant_id'], unique=False)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_external_id'))
        batch_op.drop_constraint(batch_op.f('fk_accounts_parent_id_accounts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_accounts_bank_connection_id_bank_connections'), type_='foreignkey')
        batch_op.drop_column('bic')
        batch_op.drop_column('external_id')
        batch_op.drop_column('iban')
        batch_op.drop_column('bank_connection_id')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_transactions_external_id'))
        batch_op.create_index(batch_op.f('ix_transactions_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_transactions_merchant_id_merchants'), 'merchants', ['merchant_id'], ['id'])
        batch_op.drop_column('external_id')

    op.drop_table('bank_connections')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_connections'))
    )

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_transactions_merchant_id_merchants'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_merchant_id'))
        batch_op.create_index(batch_op.f('ix_transactions_external_id'), ['external_id'], unique=1)
        batch_op.drop_column('merchant_id')

    with op.batch_alter_table('bank_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_connections_id'))
        batch_op.alter_column('provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('bank_connection_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('iban', sa.VARCHAR(length=34), nullable=True))
        batch_op.add_column(sa.Column('external_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('bic', sa.VARCHAR(length=11), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_accounts_bank_connection_id_bank_connections'), 'bank_connections', ['bank_connection_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_accounts_parent_id_accounts'), 'accounts', ['parent_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_accounts_external_id'), ['external_id'], unique=False)

    with op.batch_alter_table('merchant_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchant_aliases_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_merchant_aliases_label'))
        batch_op.drop_index(batch_op.f('ix_merchant_aliases_id'))

    op.drop_table('merchant_aliases')
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchants_name'))
        batch_op.drop_index(batch_op.f('ix_merchants_id'))

    op.drop_table('merchants')
    # ### end Alembic commands ###
