export const COUNTRIES = [
  { name: "France", code: "FRA" },
  { name: "États-Unis", code: "USA" },
  { name: "Allemagne", code: "DEU" },
  { name: "Royaume-Uni", code: "GBR" },
  { name: "Japon", code: "JPN" },
  { name: "Chine", code: "CHN" },
  { name: "Canada", code: "CAN" },
  { name: "Suisse", code: "CHE" },
  { name: "Luxembourg", code: "LUX" },
  { name: "Pays-Bas", code: "NLD" },
  { name: "Belgique", code: "BEL" },
  { name: "Espagne", code: "ESP" },
  { name: "Italie", code: "ITA" },
  { name: "Brésil", code: "BRA" },
  { name: "Inde", code: "IND" },
  { name: "Australie", code: "AUS" },
  { name: "Irlande", code: "IRL" },
  { name: "Singapour", code: "SGP" },
  { name: "Hong Kong", code: "HKG" },
  { name: "Taïwan", code: "TWN" },
  { name: "Corée du Sud", code: "KOR" },
  { name: "Monde (ETF World)", code: "WORLD" }
];
